---
sudo: required
language: objective-c

# Reference for macOS Versions:
# https://docs.travis-ci.com/user/reference/osx/#OS-X-Version
matrix:
  include:
    - os: osx
      osx_image: xcode9.4

script:
  - swift build
  - swift test
